[package]
name = "turbofish"
version = "0.0.0"
license = "MIT"
authors = ["ibraheem <ibrah1440@gmail.com>"]
edition = "2018"
description = "A fast lightweight rust framework built on top of hyper (wip)."
repository = "https://github.com/ibraheemdev/turbofish/"
readme = "README.md"

[dependencies]
futures = "0.3.6"
http = "0.2.1"
hyper = "0.13.8"
log = "0.4.11"
pin-project = "1.0.1"
regex = "1.4.2"
tokio = { version = "0.2.2", features = ["full"] }
